[theme]
base="light"
primaryColor="#0e76a8"               # 블루 포인트 컬러 (버튼, 링크)
backgroundColor="#ffffff"            # 순백색 배경
secondaryBackgroundColor="#f0f2f6"   # 밝은 회색 서브 배경 (사이드바, 컨테이너)
textColor="#262730"                  # 다크 그레이 텍스트
font="sans serif"

[secrets]
files = ["/etc/secrets/secrets.toml"]
